name       : breeze-gtk-theme
version    : 5.26.5
release    : 89
source     :
    - https://cdn.download.kde.org/stable/plasma/5.26.5/breeze-gtk-5.26.5.tar.xz : 1147ca2228144a0e6f939ca952007218b505307f0d62db3da8a92f66766633cc
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
