name       : breeze-gtk-theme
version    : 5.13.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.1/breeze-gtk-5.13.1.tar.xz : d09735ac47801d6e70bb685cea733f48455927bbd37d545acbe33352242693fd
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
