name       : breeze-gtk-theme
version    : 5.21.1
release    : 65
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.1/breeze-gtk-5.21.1.tar.xz : 6736f681411912b1347c4996aa05e24cf7beaf73331424cc3822216bd211b893
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
