name       : breeze-gtk-theme
version    : 5.9.5
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.9.5/breeze-gtk-5.9.5.tar.xz : 32dfa87f0cdf713962c22415a0ed8b2e1eff89a6fd517407738056ff32064459
license    : LGPL-2.1
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake . -DWITH_GTK3_VERSION=3.22
build      : |
    %make
install    : |
    %make_install
