name       : breeze-gtk-theme
version    : 5.27.7
release    : 93
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/breeze-gtk-5.27.7.tar.xz : 293294ed0b51c07496fe8c2ede841eb6e2ef41926725e11658c7208543d958e8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
