name       : breeze-gtk-theme
version    : 5.11.5
release    : 11
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.5/breeze-gtk-5.11.5.tar.xz : 1867bff15e5614d2b244a6c3938fef3c86ac09395e78da97aa391618f10b6d56
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
