name       : breeze-gtk-theme
version    : 5.15.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.2/breeze-gtk-5.15.2.tar.xz : 5cba7b4b0db8cc36cff4390bae197163cab2474fbcfc2833d469caeea5767d39
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
