name       : breeze-gtk-theme
version    : 5.23.3
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.3/breeze-gtk-5.23.3.tar.xz : 76bf9712d45b6f821b9174de283e2d2c3ed202ce375cd306d7d41ea9e8080373
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
