name       : breeze-gtk-theme
version    : 5.11.2
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.2/breeze-gtk-5.11.2.tar.xz : a48982e8d8cdafc8445740bac326462713222c24a387cc331accdc372dd47b30
license    : LGPL-2.1
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
