name       : breeze-gtk-theme
version    : 5.22.1
release    : 70
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.1/breeze-gtk-5.22.1.tar.xz : 07661452c7fd177210d4416f4e44f83d6f5194670dd4ced151cdedb3fa21e922
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
