name       : breeze-gtk-theme
version    : 5.27.4
release    : 90
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/breeze-gtk-5.27.4.tar.xz : cb967dcd258065f87a9cb43f8022378e7ead1db83590ca2eea4e77196226999f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/icon-fix.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
