name       : breeze-gtk-theme
version    : 5.24.4
release    : 83
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/breeze-gtk-5.24.4.tar.xz : b2fe8150a8576fb39d26b809e6b9cb06e2c2d2b039558ad75307d62ed857a168
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
