name       : breeze-gtk-theme
version    : 5.10.1
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.10.1/breeze-gtk-5.10.1.tar.xz : 53dd5e5a6178a9d1fc1aca1644dd88ae8423299981f1f00bd0fefd3a0f705bab
license    : LGPL-2.1
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake . -DWITH_GTK3_VERSION=3.22
build      : |
    %make
install    : |
    %make_install
