name       : breeze-gtk-theme
version    : 5.16.5
release    : 41
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/breeze-gtk-5.16.5.tar.xz : d9849ecf6c2fc85fde76912410ab36c46ca65b96d80b4e51819ca35015a88098
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
