name       : breeze-gtk-theme
version    : 5.23.2
release    : 77
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.2/breeze-gtk-5.23.2.tar.xz : 91156d7e5fa1afaa088f4c462eb9b8c7e04dabaf4cbaa226e93ef8facc17daab
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
