name       : breeze-gtk-theme
version    : 5.21.3
release    : 67
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.3/breeze-gtk-5.21.3.tar.xz : ac45fe545269a70aba4878fdae306d7c6a621e9f7478981f9c0b3a5a42f2abf4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
