name       : breeze-gtk-theme
version    : 5.9.3
release    : 2
source     :
    - http://download.kde.org/stable/plasma/5.9.3/breeze-gtk-5.9.3.tar.xz : 4658052abd99fedbb28ab5d6b5815e6bfa770904b8d37c1bf3a2e44729270a8b
license    : LGPL-2.1
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake . -DWITH_GTK3_VERSION=3.22
build      : |
    %make
install    : |
    %make_install
