name       : breeze-gtk-theme
version    : 5.22.2
release    : 71
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/breeze-gtk-5.22.2.1.tar.xz : 82366a4026681284fa758713700922da5dd2acf49693de4813a12b3557a788ed
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
