name       : breeze-gtk-theme
version    : 5.18.4.1
release    : 52
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.4/breeze-gtk-5.18.4.1.tar.xz : 078e0a6fe78e778f4bf34254b65a9b4cadd27ae258911f3cccde3b0498fada7f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
