name       : breeze-gtk-theme
version    : 5.22.5
release    : 74
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/breeze-gtk-5.22.5.tar.xz : c23bd1810cc491264b376f2e0187c48b4d979e2aaded7061792c35c54fd22e52
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
