name       : breeze-gtk-theme
version    : 5.17.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.3/breeze-gtk-5.17.3.tar.xz : 9b72b49a872b204522f6b65aff0504d3c40f568f3c8217d725a6c8a3867f1174
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
