name       : breeze-gtk-theme
version    : 5.11.0
release    : 6
source     :
    - https://download.kde.org/stable/plasma/5.11.0/breeze-gtk-5.11.0.tar.xz : b6352b3fe01af79a0ab097668fa34bda1513c9f1a09bbae04ff6fc813c44f83e
license    : LGPL-2.1
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
