name       : breeze-gtk-theme
version    : 5.22.4
release    : 73
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.4/breeze-gtk-5.22.4.tar.xz : 8b69b4e74594b49e3cee62fbffab875442f6b9d0d6432972b800c82eb2de87dc
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
