name       : breeze-gtk-theme
version    : 5.24.2
release    : 81
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.2/breeze-gtk-5.24.2.tar.xz : 2c1f02be02bac5d9098e90901b047ba587f57dc3827dd89b5a868ca80a2f2dc8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
