name       : breeze-gtk-theme
version    : 5.12.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/breeze-gtk-5.12.0.tar.xz : 63bb840dc97e4be3fce91da4d1ac18492b7d2f969e39657e1ef2f60565465f19
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
