name       : breeze-gtk-theme
version    : 5.17.5
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/breeze-gtk-5.17.5.tar.xz : 6dbd8e7d936840fbaf7016574d07729c9d0791711ad6d371136585ddb8f76e66
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.theme
optimize   : lto
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Breeze-Dark-as-default-gtk3-theme.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
