name       : breeze-gtk-theme
version    : 5.8.5
release    : 1
source     :
    - http://download.kde.org/stable/plasma/5.8.5/breeze-gtk-5.8.5.tar.xz : edddef80f31d58edff43100a921b980c1e68385ff36d30a056d1259e282cbd95
license    : LGPL-2.1
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake . -DWITH_GTK3_VERSION=3.22
build      : |
    %make
install    : |
    %make_install
